name: Build Specification Typst
on: push

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: spec/Sondbus.typ
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Sondbus.pdf
          path: spec/Sondbus.pdf
